name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: configure
      #   run: ./configure

      - name: make
        run: make

      - name: Archive first binary
        uses: actions/upload-artifact@v3
        with:
          name: pssm_scan-linux
          path: ./pssm_scan.exe

      - name: Archive second binary
        uses: actions/upload-artifact@v3
        with:
          name: gtf_file_region_retrieval-linux
          path: ./gtf_file_region_retrieval
