name: Build and Release Binaries

permissions:
  contents: write

on:
#  push:
#    tags:
#      - 'v*.*.*'
   release:
     types: [created]

jobs:
#  create_release:
#    name: Create release
#    runs-on: ubuntu-latest
#    outputs:
#      upload_url: ${{ steps.create_release.outputs.upload_url }}
#    steps:
##      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: true
#          prerelease: true

  build_release:
    name: Build release
#    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # macos-latest to be added
        include:
          - os: ubuntu-latest
            zip_name: pssm_scan-linux
            binary_tag: linux
            binary1: pssm_scan-linux
            binary2: gtf_file_region_retrieval-linux
            generator: UNIX Makefile
          - os: macos-latest
            zip_name: pssm_scan-mac
            binary_tag: mac
            binary1: pssm_scan-mac
            binary2: gtf_file_region_retrieval-mac
            generator: Xcode
          - os: windows-latest
            zip_name: pssm_scan-win
            binary-tag: exe
            binary1: pssm_scan.exe
            binary2: gtf_file_region_retrieval.exe
            generator: Visual Studio 16 2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel
          update: true

      - name: Install Make (Windows)
        if: matrix.os == 'windows-latest'
        run: pacman -S --noconfirm make
        shell: msys2 {0}

      - name: Install Make (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install make

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      # Build the program

      - name: Build the program (Windows)
        if: runner.os == 'Windows'
        run: make
        shell: msys2 {0}

      - name: Build the program (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: make

      - name: Build the program (MacOS)
        if: matrix.os == 'macos-latest'
        run: make CXXFLAGS="-std=gnu++2b"

      # Preparation of artifacts

      - name: Prepare artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          Copy-Item .\pssm_scan.exe -Destination artifacts\pssm_scan.exe
          Copy-Item .\gtf_file_region_retrieval.exe -Destination artifacts\gtf_file_region_retrieval.exe
        shell: pwsh

      - name: Prepare artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p artifacts
          cp ./pssm_scan artifacts/pssm_scan-linux
          cp ./gtf_file_region_retrieval artifacts/gtf_file_region_retrieval-linux
        shell: bash

      - name: Prepare artifacts (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p artifacts
          cp ./pssm_scan artifacts/pssm_scan-mac
          cp ./gtf_file_region_retrieval artifacts/gtf_file_region_retrieval-mac
        shell: bash

      # Uploads

      - name: Upload 1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #upload_url: ${{ needs.create_release.outputs.upload_url }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/${{ matrix.binary1 }}
          asset_name: ${{ matrix.binary1 }}
          asset_content_type: application/octet-stream

      - name: Upload 2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #upload_url: ${{ needs.create_release.outputs.upload_url }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: artifacts/${{ matrix.binary2 }}
          asset_name: ${{ matrix.binary2 }}
          asset_content_type: application/octet-stream
