name: Build and Release Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-toolchain
            base-devel
          update: true

      - name: Install Make (Windows)
        if: runner.os == 'Windows'
        run: pacman -S --noconfirm make
        shell: msys2 {0}

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y build-essential

      - name: Build the program (Windows)
        if: runner.os == 'Windows'
        run: make
        shell: msys2 {0}

      - name: Build the program (Linux)
        if: runner.os == 'Linux'
        run: make

      - name: Prepare artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir artifacts
          Copy-Item .\pssm_scan.exe -Destination artifacts\pssm_scan.exe
          Copy-Item .\gtf_file_region_retrieval.exe -Destination artifacts\gtf_file_region_retrieval.exe
        shell: pwsh

      - name: Prepare artifacts (Windows)
        if: runner.os == 'Linux'
        run: |
          mkdir -p artifacts
          cp ./pssm_scan artifacts/pssm_scan-linux
          cp ./gtf_file_region_retrieval artifacts/gtf_file_region_retrieval-linux
        shell: bash

      - name: Create Release
        if: github.event_name == 'push' && github.ref_type == 'tag' && matrix.os == 'ubuntu-latest'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Set upload URL (Windows)
        if: runner.os == 'Windows'
        id: set_upload_url
        run: |
          if ($env:UPLOAD_URL -ne "") {
            echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            $uploadUrl = "${{ github.event.repository.html_url }}/releases/latest"
            echo "UPLOAD_URL=$uploadUrl" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }
        shell: pwsh

      - name: Set upload URL (Linux)
        if: runner.os == 'Linux'
        id: set_upload_url
        run: |
          if [ -n "${{ steps.create_release.outputs.upload_url }}" ]; then
            echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV
          else
            echo "UPLOAD_URL=${{ github.event.repository.html_url }}/releases/latest" >> $GITHUB_ENV
          fi

      - name: Upload Release Assets first binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ runner.os == 'Windows' && 'artifacts/pssm_scan.exe' || 'artifacts/pssm_scan-linux' }}
          asset_name: ${{ runner.os == 'Windows' && 'pssm_scan.exe' || 'pssm_scan-linux' }}
          asset_content_type: application/octet-stream

      - name: Upload Release Assets second binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ${{ runner.os == 'Windows' && 'artifacts/gtf_file_region_retrieval.exe' || 'artifacts/gtf_file_region_retrieval-linux' }}
          asset_name: ${{ runner.os == 'Windows' && 'gtf_file_region_retrieval.exe' || 'gtf_file_region_retrieval-linux' }}
          asset_content_type: application/octet-stream
